import Head from 'next/head'
import { Flex, Stack, Heading, Divider } from "@chakra-ui/react"
import Hero from '../components/Hero'
import Card from '../components/Card'
import Article from '../components/Article'

export default function Home() {
  return (
    <Flex direction='column'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      {/* Projects */}
      <Stack direction='column' spacing={4} pt={10}>
        <Heading>Projects</Heading>
        <Divider />
        <Stack direction='column' spacing={8}>
          <Card
            image='/images/projects/dc_thumb.jpg'
            source='/images/projects/universe.mp4'
            heading='Domain Checker'
            description='A fraud investigation tool used to check for invalid and disposable email domains.'
            link='/projects/domainchecker'
            badge1='PYTHON'
          />
          <Card
            image='/images/projects/fd_thumb.jpg'
            source='/images/projects/universe.mp4'
            heading='Fraud Dashboard'
            description='A fraud metrics and sales dashboard created with Next.js. Designed as a data visualization tool using charts and tables.'
            link='/projects/dashboard'
            badge1='JSX'
          />
        </Stack>
      </Stack>

      {/* Articles */}
      <Stack direction='column' spacing={4} pt={10}>
        <Heading>Articles</Heading>
        <Divider />
        <Stack direction='column' spacing={8}>
          <Article
            heading='Fraud Dashboard'
            description='A fraud metrics and sales dashboard created with Next.js. Designed as a data visualization tool using charts and tables.'
            link='/test'
          />
          <Article
            heading='Fraud Dashboard'
            description='A fraud metrics and sales dashboard created with Next.js. Designed as a data visualization tool using charts and tables.'
            link='/test'
          />
        </Stack>
      </Stack>


    </Flex >
  )
}